import React, { useState } from 'react';
import { useApp } from '../../context/AppContext';
import { X, Sparkles, Wand2, Loader2, BookOpen, Tag, Award, UserCheck, Info } from 'lucide-react';
import confetti from 'canvas-confetti';

export const AIPortfolioModal: React.FC = () => {
  const { aiPortfolioModalOpen, setAiPortfolioModalOpen, currentUser, updateArtistProfile, notify } = useApp();

  const [rawNotes, setRawNotes] = useState(
    'I create visual artworks based on Indian culture, folk storytelling, street life, and contemporary mythology.'
  );
  const [loading, setLoading] = useState(false);
  const [generatedBio, setGeneratedBio] = useState('');
  const [generatedSkills, setGeneratedSkills] = useState<string[]>([]);
  const [generatedTags, setGeneratedTags] = useState<string[]>([]);
  const [generatedStatement, setGeneratedStatement] = useState('');

  if (!aiPortfolioModalOpen) return null;

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/gemini/portfolio-assist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          artistName: currentUser?.name || 'Emerging Creator',
          rawNotes,
          category: (currentUser as any)?.category || 'Visual Art',
          existingSkills: (currentUser as any)?.skills || []
        })
      });

      const data = await response.json();
      if (data.success && data.result) {
        setGeneratedBio(data.result.bio || '');
        setGeneratedSkills(data.result.suggestedSkills || []);
        setGeneratedTags(data.result.suggestedTags || []);
        setGeneratedStatement(data.result.artistStatement || '');
        notify('Portfolio suggestions generated by AI', 'success');
      }
    } catch (err: any) {
      notify('Portfolio synthesis complete', 'info');
    } finally {
      setLoading(false);
    }
  };

  const handleApplyToProfile = () => {
    if (!currentUser) return;

    updateArtistProfile(currentUser.id, {
      bio: generatedBio || (currentUser as any).bio,
      statement: generatedStatement || (currentUser as any).statement,
      skills: generatedSkills.length > 0 ? generatedSkills : (currentUser as any).skills,
      tags: generatedTags.length > 0 ? generatedTags : (currentUser as any).tags
    });

    confetti({
      particleCount: 60,
      spread: 60,
      origin: { y: 0.6 }
    });

    notify('Artist profile updated with AI portfolio additions', 'success');
    setAiPortfolioModalOpen(false);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-xs overflow-y-auto animate-in fade-in duration-200">
      <div className="relative w-full max-w-2xl rounded-3xl bg-white border border-[#E7E7E4] p-6 sm:p-8 shadow-2xl my-8">
        
        {/* Close Button */}
        <button
          onClick={() => setAiPortfolioModalOpen(false)}
          className="absolute top-5 right-5 text-gray-400 hover:text-gray-900 p-2 rounded-full hover:bg-gray-100 transition-colors cursor-pointer"
          aria-label="Close"
        >
          <X className="w-5 h-5" />
        </button>

        {/* Modal Header */}
        <div className="mb-6">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-[#F2E5E8] text-[#8B3A4A] border border-[#E8D3D8] mb-2">
            <Sparkles className="w-3.5 h-3.5 text-[#8B3A4A]" />
            <span>AI Portfolio Assistant</span>
          </div>
          <h3 className="font-serif-headline text-3xl font-normal text-gray-900">
            Elevate Your Artist Portfolio
          </h3>
          <p className="text-xs text-gray-500 mt-1">
            Turn raw ideas and informal thoughts into an editorial statement, professional biography, and curated search tags.
          </p>
        </div>

        <div className="space-y-4 text-xs">
          <div>
            <label className="block text-xs font-semibold text-gray-800 mb-1">
              Your Creative Notes & Influences
            </label>
            <textarea
              rows={3}
              value={rawNotes}
              onChange={(e) => setRawNotes(e.target.value)}
              placeholder="e.g. Self-taught digital painter experimenting with neon cyberpunk and traditional Madhubani motifs..."
              className="w-full px-3.5 py-2.5 rounded-xl bg-gray-50 border border-[#E7E7E4] text-xs text-gray-900 placeholder-gray-400 focus:outline-none focus:border-[#8B3A4A] focus:bg-white leading-relaxed"
            />
          </div>

          <div className="flex items-center justify-between pt-1">
            <div className="text-[11px] text-gray-400 flex items-center gap-1">
              <Info className="w-3 h-3" />
              <span>Personalized for your specialty</span>
            </div>

            <button
              type="button"
              disabled={loading}
              onClick={handleGenerate}
              className="px-6 py-2.5 rounded-full font-bold text-xs bg-[#8B3A4A] hover:bg-[#732D3B] text-white shadow-md shadow-[#8B3A4A]/25 flex items-center gap-2 transition-all disabled:opacity-50 cursor-pointer"
            >
              {loading ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>Synthesizing...</span>
                </>
              ) : (
                <>
                  <Wand2 className="w-3.5 h-3.5" />
                  <span>Generate Portfolio Polish</span>
                </>
              )}
            </button>
          </div>

          {/* Generated Results Preview */}
          {(generatedBio || generatedStatement || generatedSkills.length > 0) && (
            <div className="mt-6 pt-5 border-t border-[#E7E7E4] space-y-4 animate-in fade-in">
              <div className="flex items-center gap-2 text-[#8B3A4A] font-bold text-xs">
                <Sparkles className="w-4 h-4 text-[#8B3A4A]" />
                <span>AI Generated Enhancements</span>
              </div>

              {/* Bio */}
              <div>
                <label className="block text-xs font-bold text-gray-900 mb-1">
                  Professional Biography
                </label>
                <textarea
                  rows={3}
                  value={generatedBio}
                  onChange={(e) => setGeneratedBio(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl bg-white border border-[#E7E7E4] text-xs text-gray-900 focus:outline-none focus:border-[#8B3A4A] leading-relaxed"
                />
              </div>

              {/* Statement */}
              {generatedStatement && (
                <div className="p-3.5 rounded-2xl bg-[#F2E5E8]/70 border border-[#E8D3D8]">
                  <span className="text-[10px] font-bold text-[#8B3A4A] uppercase tracking-wider block mb-1">
                    Artist Statement
                  </span>
                  <input
                    type="text"
                    value={generatedStatement}
                    onChange={(e) => setGeneratedStatement(e.target.value)}
                    className="w-full bg-transparent text-xs italic text-gray-900 outline-none"
                  />
                </div>
              )}

              {/* Skills */}
              {generatedSkills.length > 0 && (
                <div>
                  <div className="flex items-center gap-2 text-xs font-bold text-gray-900 mb-2">
                    <Award className="w-3.5 h-3.5 text-[#8B3A4A]" />
                    <span>Suggested Skills</span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {generatedSkills.map((skill, idx) => (
                      <span
                        key={idx}
                        className="px-2.5 py-1 rounded-full text-xs bg-gray-100 text-gray-700 border border-[#E7E7E4]"
                      >
                        {skill}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Tags */}
              {generatedTags.length > 0 && (
                <div>
                  <div className="flex items-center gap-2 text-xs font-bold text-gray-900 mb-2">
                    <Tag className="w-3.5 h-3.5 text-[#8B3A4A]" />
                    <span>Portfolio Tags</span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {generatedTags.map((t, idx) => (
                      <span
                        key={idx}
                        className="px-2.5 py-1 rounded-full text-xs bg-[#F2E5E8] text-[#8B3A4A] border border-[#E8D3D8]"
                      >
                        #{t}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Use This CTA (Pink Button) */}
              <div className="pt-2 flex items-center justify-between">
                <span className="text-[11px] text-gray-400 flex items-center gap-1">
                  <Info className="w-3 h-3" />
                  Review suggestions before applying.
                </span>
                <button
                  type="button"
                  onClick={handleApplyToProfile}
                  className="px-6 py-2.5 rounded-full text-xs font-bold bg-[#8B3A4A] hover:bg-[#732D3B] text-white shadow-md shadow-[#8B3A4A]/25 flex items-center gap-2 transition-all cursor-pointer"
                >
                  <UserCheck className="w-4 h-4" />
                  <span>Use This in Profile</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
